### ISSUE TITLE
[Plan] Implementation

### ISSUE THREAD

**Issue by jeffchao98** [jeffchao98/kotlin-currency-practice#1]
### Main Objectives
- [x] Prepare the API token of [CurrencyLayer](https://currencylayer.com/documentation) ( #2 )
- [x] Open the new Android project in Kotlin ( #3 )
- [x] Prepare the fundamental classes ( #4 )
  - DI ( Koin ), retrofit2, ViewModel(s)
- [x] Input items ( #5 )
  - Drop-down menu
  - Text input box
- [x] Display items ( #6 )
  - Grid table
  - Cell item view
- [x] Auto-refresh feature ( #7 )
- [x] Update the readme file ( #8 )

### Sub Objective
- [x] Optimize items ( #15 )
- [x] Prepare the App Center for provide the open download source

**Comment by jeffchao98** [comment]
#### Free icon for this practice work

![coin-money-3](https://user-images.githubusercontent.com/318758/69551383-eefe7a80-0fdf-11ea-8010-a051659d0f4e.png)
